# Generated by Django 5.1.6 on 2025-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_post',
            field=models.ManyToManyField(blank=True, null=True, to='social_network.post', verbose_name='Me gusta'),
        ),
    ]
