# Generated by Django 5.1.6 on 2025-02-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_post',
            field=models.ManyToManyField(to='social_network.post', verbose_name='Me gusta'),
        ),
    ]
