# Generated by Django 5.1.6 on 2025-02-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_category_post_categort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categort',
            new_name='category',
        ),
    ]
