# Generated by Django 5.1.6 on 2025-02-27 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_rename_categort_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha publicado'),
            preserve_default=False,
        ),
    ]
