# Generated by Django 5.1.6 on 2025-02-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='Imagen'),
        ),
    ]
