# Generated by Django 5.1.6 on 2025-02-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_alter_profile_liked_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_post',
            field=models.ManyToManyField(blank=True, to='social_network.post', verbose_name='Me gusta'),
        ),
    ]
