# Generated by Django 5.1.6 on 2025-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_alter_profile_liked_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(to='social_network.profile', verbose_name='Siguiendo'),
        ),
    ]
