# Generated by Django 5.1.6 on 2025-02-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_remove_profile_following_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='social_network.profile', verbose_name='Siguiendo'),
        ),
    ]
