# Generated by Django 5.1.6 on 2025-02-28 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.profile', verbose_name='Autor'),
        ),
    ]
