# Generated by Django 5.1.6 on 2025-03-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0017_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='profiles',
            field=models.ManyToManyField(to='social_network.profile', verbose_name='Perfiles'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.profile', verbose_name='Emisor'),
        ),
    ]
