# Generated by Django 5.1.6 on 2025-03-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_remove_chat_users_chat_profiles_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
