# Generated by Django 5.1.6 on 2025-03-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0019_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.ManyToManyField(to='social_network.profile', verbose_name='Perfiles')),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('receiver_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.chat', verbose_name='Chat receptor')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.profile', verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
