# Generated by Django 5.1.6 on 2025-03-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0020_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_profile',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
