# Generated by Django 5.1.6 on 2025-03-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0022_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='profiles',
            field=models.ManyToManyField(related_name='chats', to='social_network.profile', verbose_name='Integrantes'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('receiver_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.chat', verbose_name='Chat')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_network.profile', verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
