# Generated by Django 5.1.6 on 2025-03-19 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0023_alter_chat_profiles_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Enviado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_network.chat', verbose_name='Chat'),
        ),
    ]
