# Generated by Django 5.1.7 on 2025-03-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('following', models.ManyToManyField(blank=True, to='authentication.profile', verbose_name='Siguiendo')),
            ],
        ),
    ]
